import { Inter } from "next/font/google";
import "./globals.css";
import Header  from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ACM page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav style={{display: 'flex', gap: '20px'}}>
          <a href="/">Home</a>
          <a href="/about">Sobre</a>
          <a href="/events">Eventos</a>
        </nav>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
